### ISSUE TITLE
[Feature Request] Blacklisting admin from using bot.

### ISSUE THREAD

**Issue by z4nyx** [BotsAppOfficial/BotsApp#87]
Hi is it possible to add vulnerability to blacklisting admin in the near future? The reason is admin is immune to .abl command and there is unwanted admin that abuse my bot (there is too many admins and .abl to the group command only work for non-admins) So I hope this feature would be great

**Comment by Prince-Mendiratta** [comment]
Hi @z4nyx. Firstly, the correct term to use would be functionality, instead of [vulnerability](https://www.techopedia.com/definition/13484/vulnerability).

Yes, we have plans to add such a functionality which will completely disable anyone but the bot user and sudo users from using the bot in a particular group.

**Comment by z4nyx** [comment]
> Hi @z4nyx. Firstly, the correct term to use would be functionality, instead of [vulnerability](https://www.techopedia.com/definition/13484/vulnerability).
> 
> Yes, we have plans to add such a functionality which will completely disable anyone but the bot user and sudo users from using the bot in a particular group.

Thank you so much for your reply and work. Have a nice day!
