### ISSUE TITLE
whatsapp tells me to scan qr code again 

### ISSUE THREAD

**Issue by irenik** [BotsAppOfficial/BotsApp#95]
Whatsapp tells me to scan QR code again when I try to connect the bot to my Whatsapp account and even after trying to do that it doesn't work. But it can scan QR codes for whatsapp web without issues.
Please help

**Comment by Prince-Mendiratta** [comment]
Hi @irenik . This might be due to you being subscribed to WhatsApp Multi Device. BotsApp doesn't support Multi Device yet. You can either try with a different mobile / install an older version of WhatsApp, if you're using Android.

**Comment by sarda23** [comment]
I am having a similar kind of issue. Whatsapp app android. I scan the QR code -- it says to scan again but now the QR code is not showing. this issue is only with the Microsoft Edge browser. In every other browser, the desktop app-- works.
I am using the beta.  if I leave beta -- then it works in Edge.

**Comment by Prince-Mendiratta** [comment]
Hi @sarda23. It's not about the browser, it's about using WhatsApp beta. BotsApp currently does not support WhatsApp beta so you won't be able to deploy of you're enrolled in the beta.
